/**
 * @license Copyright (c) 2003-2017, CKSource - Frederico Knabben. All rights reserved.
 * For licensing, see LICENSE.md or http://ckeditor.com/license
 */

/**
 * This file was added automatically by CKEditor builder.
 * You may re-use it at any time to build CKEditor again.
 *
 * If you would like to build CKEditor online again
 * (for example to upgrade), visit one the following links:
 *
 * (1) http://ckeditor.com/builder
 *     Visit online builder to build CKEditor from scratch.
 *
 * (2) http://ckeditor.com/builder/b7086a8ea770726c1aae7eeafa6d7c42
 *     Visit online builder to build CKEditor, starting with the same setup as before.
 *
 * (3) http://ckeditor.com/builder/download/b7086a8ea770726c1aae7eeafa6d7c42
 *     Straight download link to the latest version of CKEditor (Optimized) with the same setup as before.
 *
 * NOTE:
 *    This file is not used by CKEditor, you may remove it.
 *    Changing this file will not change your CKEditor configuration.
 */

var CKBUILDER_CONFIG = {
	skin: 'moono-dark',
	preset: 'full',
	ignore: [
		'.DS_Store',
		'.bender',
		'.editorconfig',
		'.gitattributes',
		'.gitignore',
		'.idea',
		'.jscsrc',
		'.jshintignore',
		'.jshintrc',
		'.mailmap',
		'bender-err.log',
		'bender-out.log',
		'bender.js',
		'dev',
		'gruntfile.js',
		'less',
		'node_modules',
		'package.json',
		'tests'
	],
	plugins : {
		'Audio' : 1,
		'FMathEditor' : 1,
		'SPImage' : 1,
		'SimpleImage' : 1,
		'SimpleLink' : 1,
		'Text2Speech' : 1,
		'a11yhelp' : 1,
		'about' : 1,
		'allowsave' : 1,
		'autocorrect' : 1,
		'autoembed' : 1,
		'autogrow' : 1,
		'autolink' : 1,
		'autosave' : 1,
		'backgrounds' : 1,
		'balloonpanel' : 1,
		'base64image' : 1,
		'basicstyles' : 1,
		'bbcode' : 1,
		'bgimage' : 1,
		'bidi' : 1,
		'blockquote' : 1,
		'bootstrapTabs' : 1,
		'bootstrapVisibility' : 1,
		'brclear' : 1,
		'btbutton' : 1,
		'btquicktable' : 1,
		'ccmsacdc' : 1,
		'ccmsconfighelper' : 1,
		'chart' : 1,
		'ckawesome' : 1,
		'ckeditor-gwf-plugin' : 1,
		'ckwebspeech' : 1,
		'cleanuploader' : 1,
		'clipboard' : 1,
		'closebtn' : 1,
		'codeTag' : 1,
		'codemirror' : 1,
		'codesnippetgeshi' : 1,
		'colorbutton' : 1,
		'colordialog' : 1,
		'confighelper' : 1,
		'contextmenu' : 1,
		'copyformatting' : 1,
		'crossreference' : 1,
		'cssanim' : 1,
		'custimage' : 1,
		'devtools' : 1,
		'dialogadvtab' : 1,
		'div' : 1,
		'divarea' : 1,
		'docfont' : 1,
		'dropdownmenumanager' : 1,
		'easykeymap' : 1,
		'elementspath' : 1,
		'embed' : 1,
		'embedsemantic' : 1,
		'emojione' : 1,
		'enhancedcolorbuttton' : 1,
		'enterkey' : 1,
		'entities' : 1,
		'eqneditor' : 1,
		'extraformattributes' : 1,
		'fastimage' : 1,
		'filebrowser' : 1,
		'filetools' : 1,
		'find' : 1,
		'fixed' : 1,
		'flash' : 1,
		'floating-tools' : 1,
		'floatingspace' : 1,
		'font' : 1,
		'footnotes' : 1,
		'format' : 1,
		'format_buttons' : 1,
		'forms' : 1,
		'glyphicons' : 1,
		'googledocs' : 1,
		'googlethisterm' : 1,
		'horizontalrule' : 1,
		'html5audio' : 1,
		'html5validation' : 1,
		'html5video' : 1,
		'htmlbuttons' : 1,
		'htmlwriter' : 1,
		'iframe' : 1,
		'iframedialog' : 1,
		'image' : 1,
		'imagebrowser' : 1,
		'imagepaste' : 1,
		'imageresize' : 1,
		'imageresponsive' : 1,
		'imagerotate' : 1,
		'imageuploader' : 1,
		'imgbrowse' : 1,
		'imgupload' : 1,
		'imgur' : 1,
		'indentblock' : 1,
		'indentlist' : 1,
		'inlinecancel' : 1,
		'inlinesave' : 1,
		'insertpre' : 1,
		'justify' : 1,
		'label' : 1,
		'language' : 1,
		'layoutmanager' : 1,
		'letterspacing' : 1,
		'lightbox' : 1,
		'lineheight' : 1,
		'link' : 1,
		'list' : 1,
		'liststyle' : 1,
		'liveedit' : 1,
		'magicline' : 1,
		'markdown' : 1,
		'maxheight' : 1,
		'maximize' : 1,
		'newpage' : 1,
		'niftyimages' : 1,
		'niftytimers' : 1,
		'numericinput' : 1,
		'osem_googlemaps' : 1,
		'page2images' : 1,
		'pagebreak' : 1,
		'pastecode' : 1,
		'pastefromexcel' : 1,
		'pastefromword' : 1,
		'pastetext' : 1,
		'pbckcode' : 1,
		'placeholder' : 1,
		'placeholder_select' : 1,
		'pre' : 1,
		'preview' : 1,
		'print' : 1,
		'removeformat' : 1,
		'resize' : 1,
		'resizewithwindow' : 1,
		'save' : 1,
		'scayt' : 1,
		'selectall' : 1,
		'selectallcontextmenu' : 1,
		'showblocks' : 1,
		'showborders' : 1,
		'simple-image-browser' : 1,
		'simple-ruler' : 1,
		'simplebutton' : 1,
		'sketchfab' : 1,
		'slideshow' : 1,
		'smallerselection' : 1,
		'smiley' : 1,
		'soundPlayer' : 1,
		'sourcearea' : 1,
		'sourcedialog' : 1,
		'specialchar' : 1,
		'spoiler' : 1,
		'stat' : 1,
		'staticspace' : 1,
		'stylescombo' : 1,
		'stylesheetparser' : 1,
		'stylesheetparser-fixed' : 1,
		'symbol' : 1,
		'syntaxhighlight' : 1,
		'tab' : 1,
		'tabbedimagebrowser' : 1,
		'table' : 1,
		'tableresize' : 1,
		'tabletools' : 1,
		'tabletoolstoolbar' : 1,
		'templates' : 1,
		'textselection' : 1,
		'textsignature' : 1,
		'texttransform' : 1,
		'tliyoutube2' : 1,
		'token' : 1,
		'toolbar' : 1,
		'uicolor' : 1,
		'undo' : 1,
		'videodetector' : 1,
		'wordcount' : 1,
		'wsc' : 1,
		'wysiwygarea' : 1,
		'youtube' : 1,
		'zoom' : 1
	},
	languages : {
		'en' : 1,
		'ru' : 1
	}
};